# Generated by Django 3.0.2 on 2020-02-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardiologist',
            fields=[
                ('Disease', models.CharField(choices=[('A', 'Arrhythmia'), ('C', 'Cardiomyopathy'), ('H', 'Heart Failure'), ('S', 'Stroke'), ('V', 'Vascular Disease')], max_length=250, primary_key=True, serialize=False)),
                ('Patient_id', models.CharField(max_length=250)),
                ('Consultant', models.CharField(choices=[('S', 'Sarel Burger'), ('GA', 'Garrie Snyman'), ('PH', 'Philip Nitschke'), ('MA', 'Mal Washer'), ('AD', 'Adam Finlay'), ('HI', 'Hilda Molina'), ('FR', 'Frederick Banting'), ('NO', 'Norman Bethune'), ('HU', 'Hua Tuo'), ('BI', 'Bian Que'), ('RO', 'Roberto Morales Ojeda'), ('AL', 'Aleida Guevara'), ('FR', 'Fraon Wilson'), ('DA', 'Danielle Wyatt'), ('RO', 'Robert Koch'), ('HE', 'Herta Oberheuser'), ('AK', 'Aryan Khanna'), ('VG', 'Vinay Gupta'), ('TU', 'Takashi Urasuma'), ('VE', 'Vegeta San'), ('AL', 'Alnadi Felnah'), ('BA', 'Bastaki Abdullah'), ('KI', 'Kila Pala'), ('CH', 'Charles Amini'), ('MA', 'Mariano Ponce'), ('TP', 'Trinidad Pardo'), ('NP', 'Nikolav Pirogov'), ('SB', 'Sergey Botkin'), ('KC', 'Kyle Coetzer'), ('DB', 'Dylan Budge'), ('CB', 'Christiaan Barnard'), ('JM', 'James Moroka'), ('MB', 'Millie Brown'), ('EP', 'Elsa Patakay'), ('MO', 'Mehmet Oz'), ('HB', 'Hulusi Behcet'), ('VA', 'Virginia Apgar'), ('EC', 'Elvira Chibiusa')], max_length=250)),
            ],
        ),
    ]
