# Generated by Django 3.0.2 on 2020-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dermatalogist',
            fields=[
                ('Disease', models.CharField(choices=[('A', 'Acne'), ('E', 'Eczema'), ('I', 'Ichthyosis'), ('P', 'Psoriasis'), ('S', 'Sunburn')], max_length=250, primary_key=True, serialize=False)),
                ('Patient_id', models.CharField(max_length=250)),
                ('Consultant', models.CharField(choices=[('JB', 'Jan Berrie'), ('BV', 'Burton Van Rooi'), ('BN', 'Brendan Nelson'), ('FW', 'Fiona Wood'), ('GD', 'Graciano dos Santos'), ('EB', 'Eddy Bensoussan'), ('E', 'Ernest McCulloch'), ('W', 'Wilder Penfield'), ('L', 'Li Shizhen'), ('Z', 'Zhang Zhongjinng'), ('GD', 'Gregorio Delgado'), ('LW', 'Leonard Wood'), ('BT', 'Benjamin Tennyson'), ('W', 'W.G.Grace'), ('FF', 'Fritz Fischer'), ('CW', 'Carl Weiss'), ('KR', 'Krithika Rathod'), ('GM', 'Gayathri Malhothra'), ('TM', 'Tae Matsumoto'), ('GG', 'Gohan Gennai'), ('S', 'Sikhandar Raza'), ('R', 'Rashid Khan'), ('A', 'Assad Vala'), ('S', 'Sese Bau'), ('D', 'Danilo Fernandez'), ('V', 'Vicki Belo'), ('G', 'Garviil Llizarov'), ('I', 'Ivan Pavlov'), ('M', 'Matthew Cross'), ('B', 'Bradley Wheal'), ('G', 'Glenda Grey'), ('S', 'Selig Percy Amoils'), ('C', 'Clara Alonso'), ('P', 'Pablo Picasso'), ('B', 'Brandon Stark'), ('N', 'Necati Lannister'), ('A', 'Alfred Blalock'), ('B', 'Ben Shortt')], max_length=250)),
            ],
        ),
    ]
