# Generated by Django 3.0.2 on 2020-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dermatalogist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dermatalogist',
            name='Consultant',
            field=models.CharField(choices=[('Jan Berrie', 'Jan Berrie'), ('Burton Van Rooi', 'Burton Van Rooi'), ('Brendan Nelson', 'Brendan Nelson'), ('Fiona Wood', 'Fiona Wood'), ('Graciano dos Santos', 'Graciano dos Santos'), ('Eddy Bensoussan', 'Eddy Bensoussan'), ('Ernest McCulloch', 'Ernest McCulloch'), ('Wilder Penfield', 'Wilder Penfield'), ('Li Shizhen', 'Li Shizhen'), ('Zhang Zhongjinng', 'Zhang Zhongjinng'), ('Gregorio Delgado', 'Gregorio Delgado'), ('Leonard Wood', 'Leonard Wood'), ('Benjamin Tennyson', 'Benjamin Tennyson'), ('W.G.Grace', 'W.G.Grace'), ('Fritz Fischer', 'Fritz Fischer'), ('Carl Weiss', 'Carl Weiss'), ('Krithika Rathod', 'Krithika Rathod'), ('Gayathri Malhothra', 'Gayathri Malhothra'), ('Tae Matsumoto', 'Tae Matsumoto'), ('Gohan Gennai', 'Gohan Gennai'), ('Sikhandar Raza', 'Sikhandar Raza'), ('Rashid Khan', 'Rashid Khan'), ('Assad Vala', 'Assad Vala'), ('Sese Bau', 'Sese Bau'), ('Danilo Fernandez', 'Danilo Fernandez'), ('Vicki Belo', 'Vicki Belo'), ('Garviil Llizarov', 'Garviil Llizarov'), ('Ivan Pavlov', 'Ivan Pavlov'), ('Matthew Cross', 'Matthew Cross'), ('Bradley Wheal', 'Bradley Wheal'), ('Glenda Grey', 'Glenda Grey'), ('Selig Percy Amoils', 'Selig Percy Amoils'), ('Clara Alonso', 'Clara Alonso'), ('Pablo Picasso', 'Pablo Picasso'), ('Brandon Stark', 'Brandon Stark'), ('Necati Lannister', 'Necati Lannister'), ('Alfred Blalock', 'Alfred Blalock'), ('Ben Shortt', 'Ben Shortt')], max_length=250),
        ),
        migrations.AlterField(
            model_name='dermatalogist',
            name='Disease',
            field=models.CharField(choices=[('Acne', 'Acne'), ('Eczema', 'Eczema'), ('Ichthyosis', 'Ichthyosis'), ('Psoriasis', 'Psoriasis'), ('Sunburn', 'Sunburn')], max_length=250, primary_key=True, serialize=False),
        ),
    ]
