# Generated by Django 3.0.2 on 2020-02-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gynecologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiologist',
            name='Consultant',
            field=models.CharField(choices=[('Sarel Burger', 'Sarel Burger'), ('Garrie Snyman', 'Garrie Snyman'), ('Philip Nitschke', 'Philip Nitschke'), ('Mal Washer', 'Mal Washer'), ('Adam Finlay', 'Adam Finlay'), ('Hilda Molina', 'Hilda Molina'), ('Frederick Banting', 'Frederick Banting'), ('Norman Bethune', 'Norman Bethune'), ('Hua Tuo', 'Hua Tuo'), ('Bian Que', 'Bian Que'), ('Roberto Morales Ojeda', 'Roberto Morales Ojeda'), ('Aleida Guevara', 'Aleida Guevara'), ('Fraon Wilson', 'Fraon Wilson'), ('Danielle Wyatt', 'Danielle Wyatt'), ('Robert Koch', 'Robert Koch'), ('Herta Oberheuser', 'Herta Oberheuser'), ('Aryan Khanna', 'Aryan Khanna'), ('Vinay Gupta', 'Vinay Gupta'), ('Takashi Urasuma', 'Takashi Urasuma'), ('Vegeta San', 'Vegeta San'), ('Alnadi Felnah', 'Alnadi Felnah'), ('Bastaki Abdullah', 'Bastaki Abdullah'), ('Kila Pala', 'Kila Pala'), ('Charles Amini', 'Charles Amini'), ('Mariano Ponce', 'Mariano Ponce'), ('Trinidad Pardo', 'Trinidad Pardo'), ('Nikolav Pirogov', 'Nikolav Pirogov'), ('Sergey Botkin', 'Sergey Botkin'), ('Kyle Coetzer', 'Kyle Coetzer'), ('Dylan Budge', 'Dylan Budge'), ('Christiaan Barnard', 'Christiaan Barnard'), ('James Moroka', 'James Moroka'), ('Millie Brown', 'Millie Brown'), ('Elsa Patakay', 'Elsa Patakay'), ('Mehmet Oz', 'Mehmet Oz'), ('Hulusi Behcet', 'Hulusi Behcet'), ('Virginia Apgar', 'Virginia Apgar'), ('Elvira Chibiusa', 'Elvira Chibiusa')], max_length=250),
        ),
        migrations.AlterField(
            model_name='cardiologist',
            name='Disease',
            field=models.CharField(choices=[('Arrhythmia', 'Arrhythmia'), ('Cardiomyopathy', 'Cardiomyopathy'), ('Heart Failure', 'Heart Failure'), ('Stroke', 'Stroke'), ('Vascular Disease', 'Vascular Disease')], max_length=250, primary_key=True, serialize=False),
        ),
    ]
