# Generated by Django 3.0.2 on 2020-02-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200204_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neurologist',
            fields=[
                ('Disease', models.CharField(choices=[('Alzheimer', 'Alzheimer'), ('Brain Tumour', 'Brain Tumour'), ('Epilepsy', 'Epilepsy'), ('Migrane', 'Migrane'), ('Sclerosis', 'Sclerosis')], max_length=250, primary_key=True, serialize=False)),
                ('Patient_id', models.CharField(max_length=250)),
                ('Consultant', models.CharField(choices=[('Lennie Louw', 'Lennie Louw'), ('Claude Organ', 'Claude Organ'), ('Jason Zampa', 'Jason Zampa'), ('Barry Marshall', 'Barry Marshall'), ('Mario Roberto D Poz', 'Mario Roberto D Poz'), ('Alexandre Padiha', 'Alexandre Padiha'), ('Maud Menten', 'Maud Menten'), ('Elizabeth Bagshaw', 'Elizabeth Bagshaw'), ('Gao Yaojie', 'Gao Yaojie'), ('Wong Fun', 'Wong Fun'), ('Eddie Cibrian', 'Eddie Cibrian'), ('Jose Canseco', 'Jose Canseco'), ('Jenny Gunn', 'Jenny Gunn'), ('Natalie Sciver', 'Natalie Sciver'), ('Viktor Brack', 'Viktor Brack'), ('Albert Schweitzer', 'Albert Schweitzer'), ('Manish Agarwal', 'Manish Agarwal'), ('Abhinay Sharma', 'Abhinay Sharma'), ('Aoyama Tanemichi', 'Aoyama Tanemichi'), ('Sagara Tomyasu', 'Sagara Tomyasu'), ('Alotaibi Mohammed', 'Alotaibi Mohammed'), ('Ali Zainal', 'Ali Zainal'), ('Willie Gavera', 'Willie Gavera'), ('Pipi Raho', 'Pipi Raho'), ('Jose Rizal', 'Jose Rizal'), ('Juan Flavier', 'Juan Flavier'), ('Bluma Zeigarnik', 'Bluma Zeigarnik'), ('Nadezhda Suslova', 'Nadezhda Suslova'), ('Richie Berrington', 'Richie Berrington'), ('Calum MacLeod', 'Calum MacLeod'), ('Monty Naicker', 'Monty Naicker'), ('Louis Washkansky', 'Louis Washkansky'), ('Pep Guardiola', 'Pep Guardiola'), ('Francisco Franco', 'Francisco Franco'), ('Bedrettin Yildizeli', 'Bedrettin Yildizeli'), ('Necati Celim', 'Necati Celim'), ('Bill Frist', 'Bill Frist'), ('Robin Cook', 'Robin Cook')], max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='gynecologist',
            name='Consultant',
            field=models.CharField(choices=[('Charles R Drew', 'Charles R Drew'), ('Michael Debakey', 'Michael Debakey'), ('Gazi Yasargill', 'Gazi Yasargill'), ('Zeki Uygur', 'Zeki Uygur'), ('Ariadna Gil', 'Ariadna Gil'), ('Daisy Sylvie', 'Daisy Sylvie'), ('Samantha Haggo', 'Samantha Haggo'), ('Olivia Rae', 'Olivia Rae'), ('Svyatoslav Fyodorov', 'Svyatoslav Fyodorov'), ('Vera Gedroits', 'Vera Gedroits'), ('Mariel Pontigon', 'Mariel Pontigon'), ('Leo Soriano', 'Leo Soriano'), ('Tony Ura', 'Tony Ura'), ('Dogodo Bau', 'Dogodo Bau'), ('Noor Ali Zadran', 'Noor Ali Zadran'), ('Gulbadin Naib', 'Gulbadin Naib'), ('Masazumi Harada', 'Masazumi Harada'), ('Hanaoka Seishu', 'Hanaoka Seishu'), ('Sushmitha Sinha', 'Sushmitha Sinha'), ('Parvathi Nambiyaar', 'Parvathi Nambiyaar'), ('Hermann Von Helmholtz', 'Hermann Von Helmholtz'), ('Maria Furtwangler', 'Maria Furtwangler'), ('Katherine Brun', 'Katherine Brun'), ('Georgia Elwiss', 'Georgia Elwiss'), ('Celia Cruz', 'Celia Cruz'), ('Elizabeth Pena', 'Elizabeth Pena'), ('Ji Ben', 'Ji Ben'), ('Ge Hong', 'Ge Hong'), ('Vera Peters', 'Vera Peters'), ('Augusta Cohen', 'Augusta Cohen'), ('Raquel Muniz', 'Raquel Muniz'), ('Francisca Praguer', 'Francisca Praguer'), ('James Graham', 'James Graham'), ('Alex Carey', 'Alex Carey'), ('Stefan Swanpoel', 'Stefan Swanpoel'), ('Riaan Walters', 'Riaan Walters')], max_length=250),
        ),
        migrations.AlterField(
            model_name='gynecologist',
            name='Disease',
            field=models.CharField(choices=[('Amenorrhea', 'Amenorrhea'), ('Endometriosis', 'Endometriosis'), ('Menstrual Disorders', 'Menstrual Disorders'), ('Pelvic Pain', 'Pelvic Pain'), ('Uterine Fibroids', 'Uterine Fibroids')], max_length=250, primary_key=True, serialize=False),
        ),
    ]
