# Generated by Django 3.0.2 on 2020-02-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200204_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opthalmologist',
            fields=[
                ('Disease', models.CharField(choices=[('Cataracts', 'Cataracts'), ('Conjunctivitis', 'Conjunctivitis'), ('Dry Eye', 'EpileDry Eyepsy'), ('Mascular Degenaration', 'Mascular Degenaration'), ('Retinal Disorder', 'Retinal Disorder')], max_length=250, primary_key=True, serialize=False)),
                ('Patient_id', models.CharField(max_length=250)),
                ('Consultant', models.CharField(choices=[('Sarah Romanoff', 'Sarah Romanoff'), ('Lythia Flanders', 'Lythia Flanders'), ('Ayse Olcay Tiryaki', 'Ayse Olcay Tiryaki'), ('Koray Erdogan', 'Koray Erdogan'), ('Ricky Martin', 'Ricky Martin'), ('Luis Bunuel', 'Luis Bunuel'), ('Robert Broom', 'Robert Broom'), ('Daniel Ncayiyana', 'Daniel Ncayiyana'), ('Kari Anderson', 'Kari Anderson'), ('Rachel Hawkins', 'Rachel Hawkins'), ('Christian Rakovsky', 'Christian Rakovsky'), ('Alexander Bogdanov', 'Alexander Bogdanov'), ('Ariston Bautista', 'Ariston Bautista'), ('Gedeon Quijano', 'Gedeon Quijano'), ('Jack Vare', 'Jack Vare'), ('Hiri Hiri', 'Hiri Hiri'), ('Haris Sohail', 'Haris Sohail'), ('Fahar Zaman', 'Fahar Zaman'), ('Ichiro Kamoshita', 'Ichiro Kamoshita'), ('Ogata Koan', 'Ogata Koan'), ('Shubman Gaurav', 'Shubman Gaurav'), ('Dinesh Iyer', 'Dinesh Iyer'), ('Otto Meyerhof', 'Otto Meyerhof'), ('Dorothea Erxleben', 'Dorothea Erxleben'), ('John Caius', 'John Caius'), ('Thomas Browne', 'Thomas Browne'), ('Cesar Evora', 'Cesar Evora'), ('Desi Arnaz', 'Desi Arnaz'), ('Margaret Chan', 'Margaret Chan'), ('Sun Lee', 'Sun Lee'), ('Henry Morgentaler', 'Henry Morgentaler'), ('David Sackett', 'David Sackett'), ('Rita Lobato', 'Rita Lobato'), ('Andie Steyn', 'Andie Steyn'), ('Jandira Feghali', 'Jandira Feghali'), ('Michael Wooldridge', 'Michael Wooldridge'), ('David Warner', 'David Warner'), ('Aiden Markram', 'Aiden Markram')], max_length=250)),
            ],
        ),
    ]
