# Generated by Django 3.0.2 on 2020-02-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_opthalmologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orthopedic',
            fields=[
                ('Disease', models.CharField(choices=[('Bone Fractures', 'Bone Fractures'), ('Lower Back Pain', 'Lower Back Pain'), ('Neck Pain', 'Neck Pain'), ('Osteoporosis', 'Osteoporosis'), ('Scoliosis', 'Scoliosis')], max_length=250, primary_key=True, serialize=False)),
                ('Patient_id', models.CharField(max_length=250)),
                ('Consultant', models.CharField(choices=[('Marizanne Kapp', 'Marizanne Kapp'), ('Sune Luus', 'Sune Luus'), ('Marcus Stoinis', 'Marcus Stoinis'), ('George Miller', 'George Miller'), ('Marie Durocher', 'Marie Durocher'), ('Emily Stowe', 'Emily Stowe'), ('Jennie Kidd Trout', 'Jennie Kidd Trout'), ('Brock Chisholm', 'Brock Chisholm'), ('Ma Xiaonian', 'Ma Xiaonian'), ('Ngeow Sze Chan', 'Ngeow Sze Chan'), ('Huye Batista', 'Huye Batista'), ('Jessica Moe', 'Jessica Moe'), ('Roger Bannister', 'Roger Bannister'), ('Percivall Pott', 'Percivall Pott'), ('Wolfram Sievers', 'Wolfram Sievers'), ('Karl Genzken', 'Karl Genzken'), ('Ravindra Jadeja', 'Ravindra Jadeja'), ('Vipul Kumar', 'Vipul Kumar'), ('Ryukichi Inada', 'Ryukichi Inada'), ('Keisuka Ito', 'Keisuka Ito'), ('Imad Wasim', 'Imad Wasim'), ('Mohammad Amir', 'Mohammad Amir'), ('Nosaina Pokana', 'Nosaina Pokana'), ('Lega Siaka', 'Lega Siaka'), ('Manuel S Guerrero', 'Manuel S Guerrero'), ('Zugto Riya', 'Zugto Riya'), ('Valentina Dmitryeva', 'Valentina Dmitryeva'), ('Sofiya Lisovskaia', 'Sofiya Lisovskaia'), ('Kathyrn Bryce', 'Kathyrn Bryce'), ('Sarah Bryce', 'Sarah Bryce'), ('Wouter Basson', 'Wouter Basson'), ('Mamphela Ramphele', 'Mamphela Ramphele'), ('Benicio Del Toro', 'Benicio Del Toro'), ('Penelope Cruz', 'Penelope Cruz'), ('Yildirim Aktuna', 'Yildirim Aktuna'), ('Abdullah Cevdet', 'Abdullah Cevdet'), ('William Tyrell', 'William Tyrell'), ('Thomas Starzl', 'Thomas Starzl')], max_length=250)),
            ],
        ),
    ]
