# Generated by Django 3.0.2 on 2020-02-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orthopedic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physiotherapist',
            fields=[
                ('Disease', models.CharField(choices=[('Arthiritis', 'Arthiritis'), ('Asthma', 'Asthma'), ('Back Pain', 'Back Pain'), ('Chronic Pain', 'Chronic Pain'), ('Dementia', 'Dementia')], max_length=250, primary_key=True, serialize=False)),
                ('Patient_id', models.CharField(max_length=250)),
                ('Consultant', models.CharField(choices=[('Elizabeth Blackwell', 'Elizabeth Blackwell'), ('Jonas Salk', 'Jonas Salk'), ('Serefeddin Sabuncuoglu', 'Serefeddin Sabuncuoglu'), ('Safiye Ali', 'Safiye Ali'), ('Isabella Rivera', 'Isabella Rivera'), ('Hilaria Thomas', 'Hilaria Thomas'), ('Yusuf Dadoo', 'Yusuf Dadoo'), ('Danie Keulder', 'Danie Keulder'), ('Nthato Motlana', 'Nthato Motlana'), ('Michael Jones', 'Michael Jones'), ('George Munsey', 'George Munsey'), ('Nil Filatov', 'Nil Filatov'), ('Mikhail Kogan', 'Mikhail Kogan'), ('Pacifico Marcos', 'Pacifico Marcos'), ('Ernesto Domingo', 'Ernesto Domingo'), ('Mahuru Dai', 'Mahuru Dai'), ('Vani Morea', 'Vani Morea'), ('Eissa Jassin', 'Eissa Jassin'), ('Salemm Mishary', 'Salemm Mishary'), ('Akira Koika', 'Akira Koika'), ('Yoshika Yayoi', 'Yoshika Yayoi'), ('Shivam Dube', 'Shivam Dube'), ('Ashwin Pandey', 'Ashwin Pandey'), ('Karl Brandt', 'Karl Brandt'), ('Samuel Hahnemann', 'Samuel Hahnemann'), ('Heather Knight', 'Heather Knight'), ('Luara Marsh', 'Luara Marsh'), ('Carlos Finlay', 'Carlos Finlay'), ('Juan Bruno Zayas', 'Juan Bruno Zayas'), ('Han Suyin', 'Han Suyin'), ('Chua Soi lek', 'Chua Soi lek'), ('William Osler', 'William Osler'), ('James Till', 'James Till'), ('Luara Martinez', 'Luara Martinez'), ('Darsi Ferrer', 'Darsi Ferrer'), ('Chris Hermsworth', 'Chris Hermsworth'), ('Bob Brown', 'Bob Brown'), ('Morne Karg', 'Morne Karg')], max_length=250)),
            ],
        ),
    ]
