# Generated by Django 3.0.2 on 2020-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_specilization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.CharField(max_length=300)),
                ('Consultant', models.CharField(max_length=300)),
                ('Specialization', models.CharField(choices=[('U', 'Urologist'), ('G', 'Gynecologist'), ('N', 'Neurologist'), ('C', 'Cardiologist'), ('O', 'Orthopedic Surgeon'), ('D', 'Dermatologist'), ('OP', 'Opthamalogist'), ('P', 'Physiotherapist')], max_length=300)),
                ('Disease', models.CharField(max_length=300)),
                ('Complexity', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consultant', models.CharField(max_length=300)),
                ('Specialization', models.CharField(max_length=300)),
                ('Efficiency', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Cardiologist',
        ),
        migrations.DeleteModel(
            name='Dermatalogist',
        ),
        migrations.DeleteModel(
            name='Gynecologist',
        ),
        migrations.DeleteModel(
            name='Neurologist',
        ),
        migrations.DeleteModel(
            name='Opthalmologist',
        ),
        migrations.DeleteModel(
            name='Orthopedic',
        ),
        migrations.DeleteModel(
            name='Physiotherapist',
        ),
        migrations.DeleteModel(
            name='specilization',
        ),
    ]
