# Generated by Django 3.0.2 on 2020-02-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='Specialization',
            field=models.CharField(choices=[('Urologist', 'Urologist'), ('Gynecologist', 'Gynecologist'), ('Neurologist', 'Neurologist'), ('Cardiologist', 'Cardiologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Dermatologist', 'Dermatologist'), ('Opthamalogist', 'Opthamalogist'), ('Physiotherapist', 'Physiotherapist')], max_length=300),
        ),
    ]
