# Generated by Django 3.0.2 on 2020-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200225_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='Complexity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5 ', '5 ')], max_length=300),
        ),
    ]
