# Generated by Django 3.0.2 on 2020-02-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200226_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=300)),
                ('Medication', models.CharField(max_length=300)),
                ('In_Stock', models.CharField(max_length=300)),
                ('Out_Stock', models.CharField(max_length=300)),
            ],
        ),
    ]
